### ISSUE TITLE
Game Board

### ISSUE THREAD

**Issue by Millennium-Singha** [Millennium-Singha/Knights_Royale#1]
# Description
For the initial phase of the project, the aim is to develop a basic game board for the Chess game. The game board should be implemented in Unity and should contain the necessary features to represent the game board for the player.

# Sub-Features
- Square tiles with alternating colors (black and white)
- 8 rows and 8 columns with the corresponding alphabets and numbers

# Examples

# Dependencies
- Creating a new Unity project for the game
- Setting up necessary environment for the development

# Milestones
- [ ] Implementing square tiles with alternating colors
- [ ] Implementing 8x8 rows and columns with alphabets and numbers

# Extras
- [ ] Implementation of initial position of chess pieces on game board
- [ ] AR augmentation of the game board on real-world via mobile devices

# Documentation
- [Game Concept](https://github.com/Millennium-Singha/Knights_Royale/wiki/Game-Concept)

# Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Singha) (millenniumsingha2000@gmail.com)

**Comment by Millennium-Singha** [comment]
Implemented a basic game board for the game similar to a chess board with alternating colors.

**Comment by Millennium-Singha** [comment]
Added in adjustments for the camera and scene background
